config/routes.rb
Rails.application.routes.draw do
  resources :forecasts
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  root "forecasts#index"

  resources :forecasts, only: [:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/forecast.rb
class Forecast < ApplicationRecord
  validates :street, :city, :state, :postal_code, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/forecasts_controller.rb
class ForecastsController < ApplicationController
  before_action :set_forecast, only: %i[ show edit update destroy ]

  # GET /forecasts or /forecasts.json
  def index
    @forecasts = Forecast.all.order(created_at: :desc)
  end

  # GET /forecasts/1 or /forecasts/1.json
  def show
  end

  # GET /forecasts/new
  def new
    @forecast = Forecast.new
  end

  # GET /forecasts/1/edit
  def edit
  end

  # POST /forecasts or /forecasts.json
  def create
    @forecast = Forecast.new(forecast_params)

    respond_to do |format|
      if @forecast.valid?
        @forecast.request_date = Time.now.to_formatted_s(:long)
        @forecast.temperature = WeatherService.instance.call(@forecast.postal_code)
        @forecast.save
        format.html { redirect_to forecast_url(@forecast), notice: "Forecast was successfully created." }
        format.json { render :show, status: :created, location: @forecast }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /forecasts/1 or /forecasts/1.json
  def update
    respond_to do |format|
      if @forecast.update(forecast_params)
        format.html { redirect_to forecast_url(@forecast), notice: "Forecast was successfully updated." }
        format.json { render :show, status: :ok, location: @forecast }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @forecast.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /forecasts/1 or /forecasts/1.json
  def destroy
    @forecast.destroy

    respond_to do |format|
      format.html { redirect_to forecasts_url, notice: "Forecast was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_forecast
      @forecast = Forecast.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def forecast_params
      params.require(:forecast).permit(:street, :street2, :city, :state, :postal_code, :request_date, :temperature)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/forecasts_helper.rb
module ForecastsHelper
end

app/views/forecasts/_forecast.html.erb
<div id="<%= dom_id forecast %>">
  <p>
    <strong>Street:</strong>
    <%= forecast.street %>
  </p>

  <p>
    <strong>Street2:</strong>
    <%= forecast.street2 %>
  </p>

  <p>
    <strong>City:</strong>
    <%= forecast.city %>
  </p>

  <p>
    <strong>State:</strong>
    <%= forecast.state %>
  </p>

  <p>
    <strong>Postal code:</strong>
    <%= forecast.postal_code %>
  </p>

  <p>
    <strong>Request date:</strong>
    <%= forecast.request_date %>
  </p>

  <p>
    <strong>Temperature:</strong>
    <%= forecast.temperature %>
  </p>

</div>

app/views/forecasts/_form.html.erb
<%= form_with(model: forecast) do |form| %>
  <% if forecast.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(forecast.errors.count, "error") %> prohibited this forecast from being saved:</h2>

      <ul>
        <% forecast.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :street, style: "display: block" %>
    <%= form.text_field :street %>
  </div>

  <div>
    <%= form.label :street2, style: "display: block" %>
    <%= form.text_field :street2 %>
  </div>

  <div>
    <%= form.label :city, style: "display: block" %>
    <%= form.text_field :city %>
  </div>

  <div>
    <%= form.label :state, style: "display: block" %>
    <%= form.text_field :state %>
  </div>

  <div>
    <%= form.label :postal_code, style: "display: block" %>
    <%= form.text_field :postal_code %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/forecasts/edit.html.erb
<h1>Editing forecast</h1>

<%= render "form", forecast: @forecast %>

<br>

<div>
  <%= link_to "Show this forecast", @forecast %> |
  <%= link_to "Back to forecasts", forecasts_path %>
</div>

app/views/forecasts/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Forecasts</h1>

<div id="forecasts">
  <table>
    <thead>
        <tr>
          <th> Street </th>
          <th> Street 2 </th>
          <th> City </th>
          <th> State </th>
          <th> Postal code </th>
          <th> Request date </th>
          <th> Temperature F° </th>
          <th> Actions </th>
        </tr>
    </thead>
    <tbody>
        <% @forecasts.each do |forecast| %>
            <tr>
              <td> <%= forecast.street %> </td>
              <td> <%= forecast.street2 %> </td>
              <td> <%= forecast.city %> </td>
              <td> <%= forecast.state %> </td>
              <td> <%= forecast.postal_code %> </td>
              <td> <%= forecast.request_date %> </td>
              <td> <%= forecast.temperature %> </td>
              <td> <%= link_to "Show this forecast", forecast %> </td>
            </tr>
        <% end %>
    </tbody>
  </table>
</div>

<%= link_to "New forecast", new_forecast_path %>

app/views/forecasts/new.html.erb
<h1>New forecast</h1>

<%= render "form", forecast: @forecast %>

<br>

<div>
  <%= link_to "Back to forecasts", forecasts_path %>
</div>

app/views/forecasts/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @forecast %>

<div>
  <%= link_to "Back to forecasts", forecasts_path %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Forecaster</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>